/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.verbindungsraum.cms.backend.user.ui;

import de.bite.framework.context.IContext;
import de.bite.framework.context.extension.impl.ContextType;

/**
 *
 * @author AN
 */
public class BaseCMSFrame extends javax.swing.JFrame {

    private IContext context;
    /**
     * Creates new form BaseCMSFrame
     */
    public BaseCMSFrame() {
        initComponents();
    }
    
    public void setContext(IContext context){
        this.context = context;
        this.context.getLogger().info("DI - Context gesetzt ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container_mainapp = new javax.swing.JPanel();
        picture_container = new javax.swing.JPanel();
        controlls_container = new javax.swing.JPanel();
        text_container = new javax.swing.JPanel();
        container_picturetree = new javax.swing.JPanel();
        container_dbtree = new javax.swing.JPanel();
        CMSMenuBar = new javax.swing.JMenuBar();
        Menu_Work = new javax.swing.JMenu();
        menuitem_load = new javax.swing.JMenuItem();
        menuitem_preview = new javax.swing.JMenuItem();
        menuitem_dbkonfig = new javax.swing.JMenuItem();
        Menu_Help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("nixdorfan -- content management system -- version 0.1");

        container_mainapp.setPreferredSize(new java.awt.Dimension(600, 274));
        container_mainapp.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout picture_containerLayout = new javax.swing.GroupLayout(picture_container);
        picture_container.setLayout(picture_containerLayout);
        picture_containerLayout.setHorizontalGroup(
            picture_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        picture_containerLayout.setVerticalGroup(
            picture_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        container_mainapp.add(picture_container, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout controlls_containerLayout = new javax.swing.GroupLayout(controlls_container);
        controlls_container.setLayout(controlls_containerLayout);
        controlls_containerLayout.setHorizontalGroup(
            controlls_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        controlls_containerLayout.setVerticalGroup(
            controlls_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        container_mainapp.add(controlls_container, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout text_containerLayout = new javax.swing.GroupLayout(text_container);
        text_container.setLayout(text_containerLayout);
        text_containerLayout.setHorizontalGroup(
            text_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        text_containerLayout.setVerticalGroup(
            text_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        container_mainapp.add(text_container, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(container_mainapp, java.awt.BorderLayout.CENTER);

        container_picturetree.setPreferredSize(new java.awt.Dimension(200, 274));

        javax.swing.GroupLayout container_picturetreeLayout = new javax.swing.GroupLayout(container_picturetree);
        container_picturetree.setLayout(container_picturetreeLayout);
        container_picturetreeLayout.setHorizontalGroup(
            container_picturetreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        container_picturetreeLayout.setVerticalGroup(
            container_picturetreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        getContentPane().add(container_picturetree, java.awt.BorderLayout.WEST);

        container_dbtree.setPreferredSize(new java.awt.Dimension(200, 274));

        javax.swing.GroupLayout container_dbtreeLayout = new javax.swing.GroupLayout(container_dbtree);
        container_dbtree.setLayout(container_dbtreeLayout);
        container_dbtreeLayout.setHorizontalGroup(
            container_dbtreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        container_dbtreeLayout.setVerticalGroup(
            container_dbtreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        getContentPane().add(container_dbtree, java.awt.BorderLayout.EAST);

        Menu_Work.setText("Bearbeiten");
        Menu_Work.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N

        menuitem_load.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        menuitem_load.setText("Bildverzeichnis laden");
        Menu_Work.add(menuitem_load);

        menuitem_preview.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        menuitem_preview.setText("Bildervorschau");
        Menu_Work.add(menuitem_preview);

        menuitem_dbkonfig.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        menuitem_dbkonfig.setText("Datenbank konfigurieren");
        menuitem_dbkonfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_dbkonfigActionPerformed(evt);
            }
        });
        Menu_Work.add(menuitem_dbkonfig);

        CMSMenuBar.add(Menu_Work);

        Menu_Help.setText("Hilfe");
        Menu_Help.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        CMSMenuBar.add(Menu_Help);

        setJMenuBar(CMSMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitem_dbkonfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_dbkonfigActionPerformed
        CMSDBKonfigurator dbkonf = (CMSDBKonfigurator)this.context.getObject("cms.ui.dbkonf", ContextType.NEW, null);
        dbkonf.initTree();
        dbkonf.setVisible(true);
    }//GEN-LAST:event_menuitem_dbkonfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseCMSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseCMSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseCMSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseCMSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseCMSFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar CMSMenuBar;
    private javax.swing.JMenu Menu_Help;
    private javax.swing.JMenu Menu_Work;
    private javax.swing.JPanel container_dbtree;
    private javax.swing.JPanel container_mainapp;
    private javax.swing.JPanel container_picturetree;
    private javax.swing.JPanel controlls_container;
    private javax.swing.JMenuItem menuitem_dbkonfig;
    private javax.swing.JMenuItem menuitem_load;
    private javax.swing.JMenuItem menuitem_preview;
    private javax.swing.JPanel picture_container;
    private javax.swing.JPanel text_container;
    // End of variables declaration//GEN-END:variables
}
