/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.verbindungsraum.gsal.view;

import de.bite.framework.context.IContext;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JButton;

/**
 *
 * @author AN
 */
public class GSALThreadViewer extends javax.swing.JFrame {

    private IContext context;
    /**
     * Creates new form GSALThreadViewer
     */
    public GSALThreadViewer() {
    }
    
    public void setContext(IContext context){
        this.context = context;
        initComponents();
        setUpThreadButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GSALThreadViewer  -  Aktuelle Threads");

        jPanel1.setLayout(new java.awt.GridLayout(10, 1, 5, 5));
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void setUpThreadButtons() {
        HashMap<String,Thread> threads = (HashMap<String,Thread>)this.context.getObject("executorthreads");
        for(String name : threads.keySet()){
            
            JButton jB = new JButton("Stoppe Thread " + name);
            final Thread tAct = threads.get(name);
            jB.addActionListener(new ActionListener(){

                @Override
                public void actionPerformed(ActionEvent e) {
                    tAct.interrupt();
                }
            });
            
            jPanel1.add(jB);
            
        }
        
        this.setVisible(true);
        this.pack();
    }
}
