/**
 *
 * Copyright (c) 2013.10.04
 * M-net Telekommunikations GmbH
 * 
 * @author nixdorfan
 * Java-JDK : Java(TM) SE Runtime Environment 1.7.0_04-b22
 * 
 */

package de.verbindungsraum.gsal.view;

//~--- non-JDK imports --------------------------------------------------------

import de.bite.framework.context.IContext;

//~--- JDK imports ------------------------------------------------------------

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.util.HashMap;

import javax.swing.JButton;

//~--- classes ----------------------------------------------------------------

/**
 *
 * @author AN
 */
public class GSALThreadViewer extends javax.swing.JFrame
{

  //~--- fields ---------------------------------------------------------------

  private IContext                 context;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLayeredPane jLayeredPane1;
  private javax.swing.JPanel       jPanel1;

  // End of variables declaration//GEN-END:variables

  //~--- constructors ---------------------------------------------------------

  /**
   * Creates new form GSALThreadViewer
   */
  public GSALThreadViewer() {}




  //~--- methods --------------------------------------------------------------

  /**
   * 
   * @param context IContext
   */
  public void setContext(IContext context)
  {
    this.context = context;

    initComponents();
    setUpThreadButtons();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")

  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    jLayeredPane1 = new javax.swing.JLayeredPane();
    jPanel1       = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("GSALThreadViewer  -  Aktuelle Threads");
    jPanel1.setLayout(new java.awt.GridLayout(10, 1, 5, 5));
    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    pack();
  }    // </editor-fold>//GEN-END:initComponents

  /**
   */
  private void setUpThreadButtons()
  {

    HashMap< String, Thread > threads = (HashMap< String, Thread >)this.context.getObject("executorthreads");

    for(String name : threads.keySet())
    {
      JButton      jB   = new JButton("Stoppe Thread " + name);
      final Thread tAct = threads.get(name);

      jB.addActionListener(new ActionListener()
      {
        @Override
        public void actionPerformed(ActionEvent e)
        {
          tAct.interrupt();
        }
      });
      jPanel1.add(jB);
    }

    this.setVisible(true);
    this.pack();

  }
}


/* ||\
 * ---------------------------------------------------------
 */
