/**
 *
 * Copyright (c) 2013.10.04
 * M-net Telekommunikations GmbH
 * 
 * @author nixdorfan
 * Java-JDK : Java(TM) SE Runtime Environment 1.7.0_04-b22
 * 
 */

package de.verbindungsraum.gsal.view;

//~--- non-JDK imports --------------------------------------------------------

import de.bite.framework.bootstrap.impl.Bootstrap;
import de.bite.framework.context.extension.impl.ContextStatus;
import de.bite.framework.context.IContext;

import de.verbindungsraum.gsal.threads.RAMInformationThread;
import de.verbindungsraum.gsal.threads.WatchDogStarter;
import de.verbindungsraum.gsal.utilities.BootpathLoader;

//~--- JDK imports ------------------------------------------------------------

import java.util.HashMap;

//~--- classes ----------------------------------------------------------------

/**
 *
 * @author nixdorfan
 */
public class GSALSplashScreen extends javax.swing.JFrame
{

  //~--- fields ---------------------------------------------------------------

  private String              bootpath;
  private IContext            context;

  // Variables declaration - do not modify
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel  jLabel1;
  private javax.swing.JLabel  jLabel2;
  private javax.swing.JPanel  jPanel1;
  private javax.swing.JPanel  jPanel2;
  private javax.swing.JPanel  jPanel3;
  private javax.swing.JPanel  jPanel4;
  private javax.swing.JPanel  jPanel5;
  private String              preparedConsoleValues;

  //~--- constructors ---------------------------------------------------------

  /**
   * Creates new form GSALSplashScreen
   */
  public GSALSplashScreen()
  {
    initComponents();
  }




  //~--- methods --------------------------------------------------------------

  /**
   *
   * @param preparedConsoleValues String
   */
  public void setKonfig(String preparedConsoleValues)
  {
    this.preparedConsoleValues = preparedConsoleValues;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")

  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents()
  {

    jPanel1  = new javax.swing.JPanel();
    jPanel3  = new javax.swing.JPanel();
    jPanel2  = new javax.swing.JPanel();
    jLabel1  = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jPanel4  = new javax.swing.JPanel();
    jPanel5  = new javax.swing.JPanel();
    jLabel2  = new javax.swing.JLabel();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("GSAL Splash Screen");
    jPanel1.setLayout(new java.awt.GridLayout(2, 2));
    jPanel3.setLayout(new java.awt.BorderLayout());
    jPanel2.setLayout(new java.awt.BorderLayout());
    jLabel1.setFont(new java.awt.Font("Arial", 0, 10));     // NOI18N
    jLabel1.setText("       war is peace, freedom is slavery   ");
    jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jPanel2.add(jLabel1, java.awt.BorderLayout.CENTER);
    jPanel3.add(jPanel2, java.awt.BorderLayout.CENTER);
    jPanel1.add(jPanel3);
    jButton1.setFont(new java.awt.Font("Arial", 0, 10));    // NOI18N
    jButton1.setText("Start GSAL- APP");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton1);
    jPanel4.setLayout(new java.awt.BorderLayout());
    jPanel5.setLayout(new java.awt.BorderLayout());
    jLabel2.setFont(new java.awt.Font("Arial", 0, 10));     // NOI18N
    jLabel2.setText("          ignorance is strength");
    jPanel5.add(jLabel2, java.awt.BorderLayout.CENTER);
    jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);
    jPanel1.add(jPanel4);
    jButton2.setFont(new java.awt.Font("Arial", 0, 10));    // NOI18N
    jButton2.setText("Start GSAL - CONFIG - EDITOR");
    jButton2.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        jButton2ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton2);
    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    pack();

  }    // </editor-fold>

  /**
   *
   * @param evt java.awt.event.ActionEvent
   */
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
  {

    this.context = Bootstrap.startContext(this.preparedConsoleValues);

    // TODO: Delete this hack but actual it is working
    String[] ary = this.preparedConsoleValues.split("@@@");

    for(int i = 0; i < ary.length; i++)
    {
      String[] aryParts = ary[i].split("=");

      for(int iParts = 0; i < aryParts.length; i++)
      {
        if(aryParts[0].equals("path"))
        {
          context.setObject(ContextStatus.AKTIV, aryParts[1], "basepath", null);
          this.context.getLogger().info("basepath fuer watchdog extrahiert == " + aryParts[1]);
          break;
        }
      }
    }

    HashMap< String, Thread > threads = new HashMap< String, Thread >();
    WatchDogStarter           watch   = new WatchDogStarter();
    RAMInformationThread      ram     = new RAMInformationThread();

    watch.setContext(context);
    ram.setContext(context);

    Thread t = new Thread(watch);

    t.start();
    threads.put("watchdog", t);
    this.context.getLogger().info("starting thread watchdog ... ");

    Thread t2 = new Thread(ram);

    t2.start();
    threads.put("ram", t2);
    this.context.getLogger().info("starting thread ram ... ");
    this.context.setObject("executorthreads", threads);

    /** Starte Application */

    // GSALView view = new GSALView(context, BootpathLoader.getBootPath(preparedConsoleValues));
    GSALView2nd view = new GSALView2nd();

    view.setContext(context);
    view.setPaths(BootpathLoader.getBootPath(preparedConsoleValues));
    view.setVisible(true);

  }

  /**
   *
   * @param evt java.awt.event.ActionEvent
   */
  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)
  {

    /** B o o t s t r a p Context */
    context = Bootstrap.startContext(this.preparedConsoleValues);

    /** Starte Application */
    GSALEditorView view = new GSALEditorView(context);

    view.setVisible(true);
  }

  // End of variables declaration
}


/* ||\
 * ---------------------------------------------------------
 */
